source 'https://rubygems.org'

gem 'devise'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'coffee-rails', '~> 4.0.0'
gem 'rails', '4.1.8'
gem 'rails_admin'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'sqlite3'
gem 'turbolinks'
gem 'therubyracer', :platforms => :ruby
gem 'uglifier', '>= 1.3.0'

group :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'database_rewinder'
  gem 'rspec-request_describer'
  gem 'autodoc'
  gem 'json_spec'
end

